language: node_js

node_js:
  - "8.12.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - npm cache clean
  - cd functions && npm install
  - cd ../

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
  slack: bronxbuilders:E3OdfNGm2MePIUpqDxMSnffk#travis_alerts